spring.application.name=job-application-tracker

spring.datasource.url=jdbc:sqlite:data/job_tracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true